Log in page visuals
CraftAcademy/rails_messaging_june_18 pull request #23
Opened 2018-07-04 13:50 UTC by ESteinman

### User story
```
As a user
In order to access my existing account
I would like to see a login button that takes me to a login page,
with a login form and I would like to be able to fill in the login form and click login
```
### What we have learned
Working with tables for Scenarios and tests
Working with binding-pry debugger
"Then show me the page"-command for testing
_paths in Capybara

2018-07-04 14:03 UTC, faraznaeem requested changes

2018-07-04 14:03 UTC, faraznaeem commented on features/log_in_page.feature
> +
Please use proper indentation

2018-07-04 14:03 UTC, faraznaeem commented on features/log_in_page.feature
> +
Please format the background properly for easier readability

2018-07-04 14:03 UTC, faraznaeem commented on features/log_in_page.feature
> +    When I click on 'Login'
Two `When` statements seems wrong, please refactor this and use proper indentation

2018-07-04 14:03 UTC, faraznaeem commented on features/step_definitions/basic_steps.rb
> +    end
Please format the code and use proper indentation

2018-07-04 14:28 UTC, SophieSjoberg requested changes

2018-07-04 14:28 UTC, SophieSjoberg commented on features/log_in_page.feature
> +
This User story seems unnecessary long.. How about:
"In order to access my account,
I would like to be able to log in" ??

2018-07-04 14:28 UTC, SophieSjoberg commented on features/log_in_page.feature
> +    Then I'm sent to the "Login" page
You have to assert that you will be on a specific page. "Then I should be on "Login" page"

2018-07-05 07:42 UTC, faraznaeem approved these changes

2018-07-05 07:44 UTC, SophieSjoberg approved these changes

2018-07-05 07:44 UTC, merged