(WIP) Rspec testing user sign up
CraftAcademy/rails_messaging_june_18 pull request #24
Opened 2018-07-05 08:59 UTC by Andycutter

As a user
In order to keep my information private
I would like to able to sign up for a private account

2018-07-05 14:29 UTC, SophieSjoberg requested changes

2018-07-05 14:29 UTC, SophieSjoberg commented on features/user_sign_up.feature
> +        When I fill in 'name' with 'RandomGuy'
Try with capitalised N in 'name'

2018-07-05 14:29 UTC, SophieSjoberg commented on features/step_definitions/basic_steps.rb
> +#end
Remove comment

2018-07-05 14:29 UTC, SophieSjoberg commented on features/user_sign_up.feature
> +        Then my account is created
What happens when your account is created? Are you redirected somewhere, see a message? Add that in the end of the scenario instead of `account is created`

2018-07-05 14:36 UTC, SophieSjoberg commented on features/step_definitions/user_sign_up.rb
> +end
Unused step

2018-07-05 15:26 UTC, SophieSjoberg requested changes

2018-07-05 15:26 UTC, SophieSjoberg commented on features/step_definitions/landing_page_steps.rb
> +    expect(page).to have_content something
Something?????

2018-07-05 15:27 UTC, SophieSjoberg commented on features/user_sign_up.feature
> +        And show me the page
Take the debugger away

2018-07-05 15:28 UTC, tochman commented on features/step_definitions/user_sign_up.rb
> +    User.create(user)
Please use the factory for user here

2018-07-05 15:28 UTC, tochman commented on features/step_definitions/user_sign_up.rb
> +  end
No need for the if statement if you don’t set the path variable value in the step

2018-07-05 15:28 UTC, tochman commented on spec/rails_helper.rb
> +#require 'support/factory_bot'
Please remove comments

2018-07-05 15:39 UTC, SophieSjoberg approved these changes

2018-07-05 15:39 UTC, SophieSjoberg commented
LGTM 👍

2018-07-06 08:48 UTC, ESteinman commented on features/step_definitions/user_sign_up.rb
> +    User.create(user)
Done

2018-07-06 08:49 UTC, ESteinman commented on features/step_definitions/user_sign_up.rb
> +  end
Done

2018-07-06 08:49 UTC, ESteinman commented on spec/rails_helper.rb
> +#require 'support/factory_bot'
Done

2018-07-06 09:36 UTC, faraznaeem commented on spec/models/user_sign_up_spec.rb
> +
Do you need both spec helper and rails helper?

2018-07-06 09:36 UTC, faraznaeem commented on features/step_definitions/landing_page_steps.rb
> +    expect(page).to have_content application_name
What do mean with `application_name`?

2018-07-06 09:41 UTC, faraznaeem approved these changes

2018-07-06 09:41 UTC, merged